name: SimpleVote
version: '1.0-SNAPSHOT'
main: com.jellypudding.simpleVote.SimpleVote
api-version: '1.21'
description: A simple vote plugin that rewards players with tokens when they vote for your server.
author: AlphaAlex115

commands:
  tokens:
    description: Check or manage your vote tokens
    usage: /<command> [player]
    aliases: [votetoken, votetokens]
  votekey:
    description: Display the public key for registering on voting sites
    usage: /<command>
    permission: simplevote.admin
  testvote:
    description: Simulate a vote (for testing only)
    usage: /<command>
    permission: simplevote.admin

permissions:
  simplevote.check:
    description: Allows checking own token balance
    default: true
  simplevote.check.others:
    description: Allows checking others' token balances
    default: op
  simplevote.admin:
    description: Allows managing tokens for all players
    default: op
