name: SimpleVote
version: '2.3'
main: com.jellypudding.simpleVote.SimpleVote
api-version: '1.21'
description: A simple vote plugin that rewards players with tokens when they vote for your server.
author: AlphaAlex115
website: www.minecraftoffline.net

commands:
  tokens:
    description: Check your vote token balance
    usage: /<command>
    aliases: [votetoken, votetokens]
    permission: simplevote.tokens
  votesites:
    description: Display a list of voting sites as clickable links
    usage: /<command>
    aliases: [vote, votes]
    permission: simplevote.votesites
  votekey:
    description: Display the public key for registering on voting sites
    usage: /<command>
    permission: simplevote.admin

permissions:
  simplevote.tokens:
    description: Allows checking own token balance
    default: true
  simplevote.tokens.others:
    description: Allows checking others' token balances
    default: op
  simplevote.votesites:
    description: Allows viewing voting sites
    default: true
  simplevote.admin:
    description: Allows managing tokens for all players and accessing admin commands
    default: op
